export interface ILocation {
	id: string;
	createdAt: string;
	updatedAt: string;
	name: string;
	placeId: string;
	googleId: string;
	city: string;
	country: string;
	flag: string;
	emoji: string;
	coordinates: string;
	address: string;
	bestTimeToVisit: string;
	typicalTimeSpent: string;
	businessStatus: string;
	locationLink: string;
	type: string;
	description: string;
	openingHours: string;
	phone: string;
	website: string;
	reviewsCount: number;
	reviewsAverage: number;
	priceRange: string;
	photo: string;
	tips: string[] | null;
	highlights: string[] | null;
	categories: string[] | null;
	mustTryDishes: string[] | null;
}
